// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SECOND_SAMPLE_H_
#define FLATBUFFERS_GENERATED_SECOND_SAMPLE_H_

#include "flatbuffers/flatbuffers.h"

namespace Sample {

struct Born2;
struct Born2Builder;

struct Car2;
struct Car2Builder;

struct Home2;
struct Home2Builder;

struct PersonSecond;
struct PersonSecondBuilder;

struct Born2 FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef Born2Builder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DATE = 4,
    VT_CITY = 6,
    VT_HOSPITAL_NAME = 8,
    VT_FATHER_NAME = 10
  };
  const flatbuffers::String *date() const {
    return GetPointer<const flatbuffers::String *>(VT_DATE);
  }
  const flatbuffers::String *city() const {
    return GetPointer<const flatbuffers::String *>(VT_CITY);
  }
  const flatbuffers::String *hospital_name() const {
    return GetPointer<const flatbuffers::String *>(VT_HOSPITAL_NAME);
  }
  const flatbuffers::String *father_name() const {
    return GetPointer<const flatbuffers::String *>(VT_FATHER_NAME);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_DATE) &&
           verifier.VerifyString(date()) &&
           VerifyOffset(verifier, VT_CITY) &&
           verifier.VerifyString(city()) &&
           VerifyOffset(verifier, VT_HOSPITAL_NAME) &&
           verifier.VerifyString(hospital_name()) &&
           VerifyOffset(verifier, VT_FATHER_NAME) &&
           verifier.VerifyString(father_name()) &&
           verifier.EndTable();
  }
};

struct Born2Builder {
  typedef Born2 Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_date(flatbuffers::Offset<flatbuffers::String> date) {
    fbb_.AddOffset(Born2::VT_DATE, date);
  }
  void add_city(flatbuffers::Offset<flatbuffers::String> city) {
    fbb_.AddOffset(Born2::VT_CITY, city);
  }
  void add_hospital_name(flatbuffers::Offset<flatbuffers::String> hospital_name) {
    fbb_.AddOffset(Born2::VT_HOSPITAL_NAME, hospital_name);
  }
  void add_father_name(flatbuffers::Offset<flatbuffers::String> father_name) {
    fbb_.AddOffset(Born2::VT_FATHER_NAME, father_name);
  }
  explicit Born2Builder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Born2> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Born2>(end);
    return o;
  }
};

inline flatbuffers::Offset<Born2> CreateBorn2(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> date = 0,
    flatbuffers::Offset<flatbuffers::String> city = 0,
    flatbuffers::Offset<flatbuffers::String> hospital_name = 0,
    flatbuffers::Offset<flatbuffers::String> father_name = 0) {
  Born2Builder builder_(_fbb);
  builder_.add_father_name(father_name);
  builder_.add_hospital_name(hospital_name);
  builder_.add_city(city);
  builder_.add_date(date);
  return builder_.Finish();
}

inline flatbuffers::Offset<Born2> CreateBorn2Direct(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *date = nullptr,
    const char *city = nullptr,
    const char *hospital_name = nullptr,
    const char *father_name = nullptr) {
  auto date__ = date ? _fbb.CreateString(date) : 0;
  auto city__ = city ? _fbb.CreateString(city) : 0;
  auto hospital_name__ = hospital_name ? _fbb.CreateString(hospital_name) : 0;
  auto father_name__ = father_name ? _fbb.CreateString(father_name) : 0;
  return Sample::CreateBorn2(
      _fbb,
      date__,
      city__,
      hospital_name__,
      father_name__);
}

struct Car2 FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef Car2Builder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MODEL_NAME = 4,
    VT_FACTORY_YEAR = 6,
    VT_LICENSE_PLATE = 8
  };
  const flatbuffers::String *model_name() const {
    return GetPointer<const flatbuffers::String *>(VT_MODEL_NAME);
  }
  int32_t factory_year() const {
    return GetField<int32_t>(VT_FACTORY_YEAR, 0);
  }
  const flatbuffers::String *license_plate() const {
    return GetPointer<const flatbuffers::String *>(VT_LICENSE_PLATE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_MODEL_NAME) &&
           verifier.VerifyString(model_name()) &&
           VerifyField<int32_t>(verifier, VT_FACTORY_YEAR) &&
           VerifyOffset(verifier, VT_LICENSE_PLATE) &&
           verifier.VerifyString(license_plate()) &&
           verifier.EndTable();
  }
};

struct Car2Builder {
  typedef Car2 Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_model_name(flatbuffers::Offset<flatbuffers::String> model_name) {
    fbb_.AddOffset(Car2::VT_MODEL_NAME, model_name);
  }
  void add_factory_year(int32_t factory_year) {
    fbb_.AddElement<int32_t>(Car2::VT_FACTORY_YEAR, factory_year, 0);
  }
  void add_license_plate(flatbuffers::Offset<flatbuffers::String> license_plate) {
    fbb_.AddOffset(Car2::VT_LICENSE_PLATE, license_plate);
  }
  explicit Car2Builder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Car2> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Car2>(end);
    return o;
  }
};

inline flatbuffers::Offset<Car2> CreateCar2(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> model_name = 0,
    int32_t factory_year = 0,
    flatbuffers::Offset<flatbuffers::String> license_plate = 0) {
  Car2Builder builder_(_fbb);
  builder_.add_license_plate(license_plate);
  builder_.add_factory_year(factory_year);
  builder_.add_model_name(model_name);
  return builder_.Finish();
}

inline flatbuffers::Offset<Car2> CreateCar2Direct(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *model_name = nullptr,
    int32_t factory_year = 0,
    const char *license_plate = nullptr) {
  auto model_name__ = model_name ? _fbb.CreateString(model_name) : 0;
  auto license_plate__ = license_plate ? _fbb.CreateString(license_plate) : 0;
  return Sample::CreateCar2(
      _fbb,
      model_name__,
      factory_year,
      license_plate__);
}

struct Home2 FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef Home2Builder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ADDRESS = 4,
    VT_OWNERSHIP = 6
  };
  const flatbuffers::String *address() const {
    return GetPointer<const flatbuffers::String *>(VT_ADDRESS);
  }
  const flatbuffers::String *ownership() const {
    return GetPointer<const flatbuffers::String *>(VT_OWNERSHIP);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ADDRESS) &&
           verifier.VerifyString(address()) &&
           VerifyOffset(verifier, VT_OWNERSHIP) &&
           verifier.VerifyString(ownership()) &&
           verifier.EndTable();
  }
};

struct Home2Builder {
  typedef Home2 Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_address(flatbuffers::Offset<flatbuffers::String> address) {
    fbb_.AddOffset(Home2::VT_ADDRESS, address);
  }
  void add_ownership(flatbuffers::Offset<flatbuffers::String> ownership) {
    fbb_.AddOffset(Home2::VT_OWNERSHIP, ownership);
  }
  explicit Home2Builder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Home2> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Home2>(end);
    return o;
  }
};

inline flatbuffers::Offset<Home2> CreateHome2(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> address = 0,
    flatbuffers::Offset<flatbuffers::String> ownership = 0) {
  Home2Builder builder_(_fbb);
  builder_.add_ownership(ownership);
  builder_.add_address(address);
  return builder_.Finish();
}

inline flatbuffers::Offset<Home2> CreateHome2Direct(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *address = nullptr,
    const char *ownership = nullptr) {
  auto address__ = address ? _fbb.CreateString(address) : 0;
  auto ownership__ = ownership ? _fbb.CreateString(ownership) : 0;
  return Sample::CreateHome2(
      _fbb,
      address__,
      ownership__);
}

struct PersonSecond FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef PersonSecondBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_BORN = 6,
    VT_CAR = 8,
    VT_HOME = 10
  };
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  const Sample::Born2 *born() const {
    return GetPointer<const Sample::Born2 *>(VT_BORN);
  }
  const Sample::Car2 *car() const {
    return GetPointer<const Sample::Car2 *>(VT_CAR);
  }
  const Sample::Home2 *home() const {
    return GetPointer<const Sample::Home2 *>(VT_HOME);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_BORN) &&
           verifier.VerifyTable(born()) &&
           VerifyOffset(verifier, VT_CAR) &&
           verifier.VerifyTable(car()) &&
           VerifyOffset(verifier, VT_HOME) &&
           verifier.VerifyTable(home()) &&
           verifier.EndTable();
  }
};

struct PersonSecondBuilder {
  typedef PersonSecond Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(PersonSecond::VT_NAME, name);
  }
  void add_born(flatbuffers::Offset<Sample::Born2> born) {
    fbb_.AddOffset(PersonSecond::VT_BORN, born);
  }
  void add_car(flatbuffers::Offset<Sample::Car2> car) {
    fbb_.AddOffset(PersonSecond::VT_CAR, car);
  }
  void add_home(flatbuffers::Offset<Sample::Home2> home) {
    fbb_.AddOffset(PersonSecond::VT_HOME, home);
  }
  explicit PersonSecondBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<PersonSecond> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<PersonSecond>(end);
    return o;
  }
};

inline flatbuffers::Offset<PersonSecond> CreatePersonSecond(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    flatbuffers::Offset<Sample::Born2> born = 0,
    flatbuffers::Offset<Sample::Car2> car = 0,
    flatbuffers::Offset<Sample::Home2> home = 0) {
  PersonSecondBuilder builder_(_fbb);
  builder_.add_home(home);
  builder_.add_car(car);
  builder_.add_born(born);
  builder_.add_name(name);
  return builder_.Finish();
}

inline flatbuffers::Offset<PersonSecond> CreatePersonSecondDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    flatbuffers::Offset<Sample::Born2> born = 0,
    flatbuffers::Offset<Sample::Car2> car = 0,
    flatbuffers::Offset<Sample::Home2> home = 0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return Sample::CreatePersonSecond(
      _fbb,
      name__,
      born,
      car,
      home);
}

inline const Sample::PersonSecond *GetPersonSecond(const void *buf) {
  return flatbuffers::GetRoot<Sample::PersonSecond>(buf);
}

inline const Sample::PersonSecond *GetSizePrefixedPersonSecond(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<Sample::PersonSecond>(buf);
}

inline bool VerifyPersonSecondBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Sample::PersonSecond>(nullptr);
}

inline bool VerifySizePrefixedPersonSecondBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Sample::PersonSecond>(nullptr);
}

inline void FinishPersonSecondBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<Sample::PersonSecond> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedPersonSecondBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<Sample::PersonSecond> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Sample

#endif  // FLATBUFFERS_GENERATED_SECOND_SAMPLE_H_
