// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: first.proto
// Protobuf C++ Version: 6.33.0-dev

#ifndef first_2eproto_2epb_2eh
#define first_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_first_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_first_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_first_2eproto;
}  // extern "C"
namespace sample {
class Born;
struct BornDefaultTypeInternal;
extern BornDefaultTypeInternal _Born_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Born_class_data_;
class Car;
struct CarDefaultTypeInternal;
extern CarDefaultTypeInternal _Car_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Car_class_data_;
class Home;
struct HomeDefaultTypeInternal;
extern HomeDefaultTypeInternal _Home_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Home_class_data_;
class PeopleFirst;
struct PeopleFirstDefaultTypeInternal;
extern PeopleFirstDefaultTypeInternal _PeopleFirst_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PeopleFirst_class_data_;
class PersonFirst;
struct PersonFirstDefaultTypeInternal;
extern PersonFirstDefaultTypeInternal _PersonFirst_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PersonFirst_class_data_;
}  // namespace sample
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace sample {

// ===================================================================


// -------------------------------------------------------------------

class Home final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:sample.Home) */ {
 public:
  inline Home() : Home(nullptr) {}
  ~Home() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Home* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Home));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Home(::google::protobuf::internal::ConstantInitialized);

  inline Home(const Home& from) : Home(nullptr, from) {}
  inline Home(Home&& from) noexcept
      : Home(nullptr, ::std::move(from)) {}
  inline Home& operator=(const Home& from) {
    CopyFrom(from);
    return *this;
  }
  inline Home& operator=(Home&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Home& default_instance() {
    return *reinterpret_cast<const Home*>(
        &_Home_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(Home& a, Home& b) { a.Swap(&b); }
  inline void Swap(Home* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Home* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Home* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Home>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Home& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Home& from) { Home::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Home* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "sample.Home"; }

  explicit Home(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Home(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Home& from);
  Home(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Home&& from) noexcept
      : Home(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kAddressFieldNumber = 1,
    kOwnershipFieldNumber = 2,
  };
  // string address = 1;
  void clear_address() ;
  const ::std::string& address() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_address(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_address();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_address();
  void set_allocated_address(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_address() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_address(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_address();

  public:
  // string ownership = 2;
  void clear_ownership() ;
  const ::std::string& ownership() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_ownership(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_ownership();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_ownership();
  void set_allocated_ownership(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_ownership() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_ownership(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_ownership();

  public:
  // @@protoc_insertion_point(class_scope:sample.Home)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 36,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Home& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr address_;
    ::google::protobuf::internal::ArenaStringPtr ownership_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_first_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Home_class_data_;
// -------------------------------------------------------------------

class Car final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:sample.Car) */ {
 public:
  inline Car() : Car(nullptr) {}
  ~Car() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Car* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Car));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Car(::google::protobuf::internal::ConstantInitialized);

  inline Car(const Car& from) : Car(nullptr, from) {}
  inline Car(Car&& from) noexcept
      : Car(nullptr, ::std::move(from)) {}
  inline Car& operator=(const Car& from) {
    CopyFrom(from);
    return *this;
  }
  inline Car& operator=(Car&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Car& default_instance() {
    return *reinterpret_cast<const Car*>(
        &_Car_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(Car& a, Car& b) { a.Swap(&b); }
  inline void Swap(Car* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Car* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Car* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Car>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Car& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Car& from) { Car::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Car* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "sample.Car"; }

  explicit Car(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Car(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Car& from);
  Car(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Car&& from) noexcept
      : Car(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kModelNameFieldNumber = 1,
    kLicensePlateFieldNumber = 3,
    kFactoryYearFieldNumber = 2,
  };
  // string model_name = 1;
  void clear_model_name() ;
  const ::std::string& model_name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_model_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_model_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_model_name();
  void set_allocated_model_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_model_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_model_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_model_name();

  public:
  // string license_plate = 3;
  void clear_license_plate() ;
  const ::std::string& license_plate() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_license_plate(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_license_plate();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_license_plate();
  void set_allocated_license_plate(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_license_plate() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_license_plate(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_license_plate();

  public:
  // int32 factory_year = 2;
  void clear_factory_year() ;
  ::int32_t factory_year() const;
  void set_factory_year(::int32_t value);

  private:
  ::int32_t _internal_factory_year() const;
  void _internal_set_factory_year(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:sample.Car)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 42,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Car& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr model_name_;
    ::google::protobuf::internal::ArenaStringPtr license_plate_;
    ::int32_t factory_year_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_first_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Car_class_data_;
// -------------------------------------------------------------------

class Born final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:sample.Born) */ {
 public:
  inline Born() : Born(nullptr) {}
  ~Born() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Born* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Born));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Born(::google::protobuf::internal::ConstantInitialized);

  inline Born(const Born& from) : Born(nullptr, from) {}
  inline Born(Born&& from) noexcept
      : Born(nullptr, ::std::move(from)) {}
  inline Born& operator=(const Born& from) {
    CopyFrom(from);
    return *this;
  }
  inline Born& operator=(Born&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Born& default_instance() {
    return *reinterpret_cast<const Born*>(
        &_Born_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Born& a, Born& b) { a.Swap(&b); }
  inline void Swap(Born* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Born* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Born* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Born>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Born& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Born& from) { Born::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Born* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "sample.Born"; }

  explicit Born(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Born(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Born& from);
  Born(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Born&& from) noexcept
      : Born(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDateFieldNumber = 1,
    kCityFieldNumber = 2,
  };
  // string date = 1;
  void clear_date() ;
  const ::std::string& date() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_date(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_date();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_date();
  void set_allocated_date(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_date() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_date(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_date();

  public:
  // string city = 2;
  void clear_city() ;
  const ::std::string& city() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_city(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_city();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_city();
  void set_allocated_city(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_city() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_city(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_city();

  public:
  // @@protoc_insertion_point(class_scope:sample.Born)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 28,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Born& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr date_;
    ::google::protobuf::internal::ArenaStringPtr city_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_first_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Born_class_data_;
// -------------------------------------------------------------------

class PersonFirst final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:sample.PersonFirst) */ {
 public:
  inline PersonFirst() : PersonFirst(nullptr) {}
  ~PersonFirst() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PersonFirst* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PersonFirst));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PersonFirst(::google::protobuf::internal::ConstantInitialized);

  inline PersonFirst(const PersonFirst& from) : PersonFirst(nullptr, from) {}
  inline PersonFirst(PersonFirst&& from) noexcept
      : PersonFirst(nullptr, ::std::move(from)) {}
  inline PersonFirst& operator=(const PersonFirst& from) {
    CopyFrom(from);
    return *this;
  }
  inline PersonFirst& operator=(PersonFirst&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PersonFirst& default_instance() {
    return *reinterpret_cast<const PersonFirst*>(
        &_PersonFirst_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(PersonFirst& a, PersonFirst& b) { a.Swap(&b); }
  inline void Swap(PersonFirst* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PersonFirst* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PersonFirst* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PersonFirst>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PersonFirst& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PersonFirst& from) { PersonFirst::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PersonFirst* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "sample.PersonFirst"; }

  explicit PersonFirst(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PersonFirst(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PersonFirst& from);
  PersonFirst(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PersonFirst&& from) noexcept
      : PersonFirst(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNameFieldNumber = 1,
    kJobFieldNumber = 5,
    kBornFieldNumber = 2,
    kCarFieldNumber = 3,
    kHomeFieldNumber = 4,
  };
  // string name = 1;
  void clear_name() ;
  const ::std::string& name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_name();
  void set_allocated_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_name();

  public:
  // string job = 5;
  void clear_job() ;
  const ::std::string& job() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_job(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_job();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_job();
  void set_allocated_job(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_job() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_job(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_job();

  public:
  // .sample.Born born = 2;
  bool has_born() const;
  void clear_born() ;
  const ::sample::Born& born() const;
  [[nodiscard]] ::sample::Born* PROTOBUF_NULLABLE release_born();
  ::sample::Born* PROTOBUF_NONNULL mutable_born();
  void set_allocated_born(::sample::Born* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_born(::sample::Born* PROTOBUF_NULLABLE value);
  ::sample::Born* PROTOBUF_NULLABLE unsafe_arena_release_born();

  private:
  const ::sample::Born& _internal_born() const;
  ::sample::Born* PROTOBUF_NONNULL _internal_mutable_born();

  public:
  // .sample.Car car = 3;
  bool has_car() const;
  void clear_car() ;
  const ::sample::Car& car() const;
  [[nodiscard]] ::sample::Car* PROTOBUF_NULLABLE release_car();
  ::sample::Car* PROTOBUF_NONNULL mutable_car();
  void set_allocated_car(::sample::Car* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_car(::sample::Car* PROTOBUF_NULLABLE value);
  ::sample::Car* PROTOBUF_NULLABLE unsafe_arena_release_car();

  private:
  const ::sample::Car& _internal_car() const;
  ::sample::Car* PROTOBUF_NONNULL _internal_mutable_car();

  public:
  // .sample.Home home = 4;
  bool has_home() const;
  void clear_home() ;
  const ::sample::Home& home() const;
  [[nodiscard]] ::sample::Home* PROTOBUF_NULLABLE release_home();
  ::sample::Home* PROTOBUF_NONNULL mutable_home();
  void set_allocated_home(::sample::Home* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_home(::sample::Home* PROTOBUF_NULLABLE value);
  ::sample::Home* PROTOBUF_NULLABLE unsafe_arena_release_home();

  private:
  const ::sample::Home& _internal_home() const;
  ::sample::Home* PROTOBUF_NONNULL _internal_mutable_home();

  public:
  // @@protoc_insertion_point(class_scope:sample.PersonFirst)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   3, 34,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PersonFirst& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::google::protobuf::internal::ArenaStringPtr job_;
    ::sample::Born* PROTOBUF_NULLABLE born_;
    ::sample::Car* PROTOBUF_NULLABLE car_;
    ::sample::Home* PROTOBUF_NULLABLE home_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_first_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PersonFirst_class_data_;
// -------------------------------------------------------------------

class PeopleFirst final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:sample.PeopleFirst) */ {
 public:
  inline PeopleFirst() : PeopleFirst(nullptr) {}
  ~PeopleFirst() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PeopleFirst* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PeopleFirst));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PeopleFirst(::google::protobuf::internal::ConstantInitialized);

  inline PeopleFirst(const PeopleFirst& from) : PeopleFirst(nullptr, from) {}
  inline PeopleFirst(PeopleFirst&& from) noexcept
      : PeopleFirst(nullptr, ::std::move(from)) {}
  inline PeopleFirst& operator=(const PeopleFirst& from) {
    CopyFrom(from);
    return *this;
  }
  inline PeopleFirst& operator=(PeopleFirst&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PeopleFirst& default_instance() {
    return *reinterpret_cast<const PeopleFirst*>(
        &_PeopleFirst_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(PeopleFirst& a, PeopleFirst& b) { a.Swap(&b); }
  inline void Swap(PeopleFirst* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PeopleFirst* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PeopleFirst* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PeopleFirst>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PeopleFirst& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PeopleFirst& from) { PeopleFirst::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PeopleFirst* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "sample.PeopleFirst"; }

  explicit PeopleFirst(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PeopleFirst(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PeopleFirst& from);
  PeopleFirst(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PeopleFirst&& from) noexcept
      : PeopleFirst(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPeopleFieldNumber = 1,
  };
  // repeated .sample.PersonFirst people = 1;
  int people_size() const;
  private:
  int _internal_people_size() const;

  public:
  void clear_people() ;
  ::sample::PersonFirst* PROTOBUF_NONNULL mutable_people(int index);
  ::google::protobuf::RepeatedPtrField<::sample::PersonFirst>* PROTOBUF_NONNULL mutable_people();

  private:
  const ::google::protobuf::RepeatedPtrField<::sample::PersonFirst>& _internal_people() const;
  ::google::protobuf::RepeatedPtrField<::sample::PersonFirst>* PROTOBUF_NONNULL _internal_mutable_people();
  public:
  const ::sample::PersonFirst& people(int index) const;
  ::sample::PersonFirst* PROTOBUF_NONNULL add_people();
  const ::google::protobuf::RepeatedPtrField<::sample::PersonFirst>& people() const;
  // @@protoc_insertion_point(class_scope:sample.PeopleFirst)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PeopleFirst& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::sample::PersonFirst > people_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_first_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PeopleFirst_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Born

// string date = 1;
inline void Born::clear_date() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.date_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& Born::date() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:sample.Born.date)
  return _internal_date();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Born::set_date(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.date_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:sample.Born.date)
}
inline ::std::string* PROTOBUF_NONNULL Born::mutable_date()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_date();
  // @@protoc_insertion_point(field_mutable:sample.Born.date)
  return _s;
}
inline const ::std::string& Born::_internal_date() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.date_.Get();
}
inline void Born::_internal_set_date(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.date_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Born::_internal_mutable_date() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.date_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Born::release_date() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:sample.Born.date)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.date_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.date_.Set("", GetArena());
  }
  return released;
}
inline void Born::set_allocated_date(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.date_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.date_.IsDefault()) {
    _impl_.date_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:sample.Born.date)
}

// string city = 2;
inline void Born::clear_city() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.city_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& Born::city() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:sample.Born.city)
  return _internal_city();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Born::set_city(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.city_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:sample.Born.city)
}
inline ::std::string* PROTOBUF_NONNULL Born::mutable_city()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_city();
  // @@protoc_insertion_point(field_mutable:sample.Born.city)
  return _s;
}
inline const ::std::string& Born::_internal_city() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.city_.Get();
}
inline void Born::_internal_set_city(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.city_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Born::_internal_mutable_city() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.city_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Born::release_city() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:sample.Born.city)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.city_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.city_.Set("", GetArena());
  }
  return released;
}
inline void Born::set_allocated_city(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.city_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.city_.IsDefault()) {
    _impl_.city_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:sample.Born.city)
}

// -------------------------------------------------------------------

// Car

// string model_name = 1;
inline void Car::clear_model_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.model_name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& Car::model_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:sample.Car.model_name)
  return _internal_model_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Car::set_model_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.model_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:sample.Car.model_name)
}
inline ::std::string* PROTOBUF_NONNULL Car::mutable_model_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_model_name();
  // @@protoc_insertion_point(field_mutable:sample.Car.model_name)
  return _s;
}
inline const ::std::string& Car::_internal_model_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.model_name_.Get();
}
inline void Car::_internal_set_model_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.model_name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Car::_internal_mutable_model_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.model_name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Car::release_model_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:sample.Car.model_name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.model_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.model_name_.Set("", GetArena());
  }
  return released;
}
inline void Car::set_allocated_model_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.model_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.model_name_.IsDefault()) {
    _impl_.model_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:sample.Car.model_name)
}

// int32 factory_year = 2;
inline void Car::clear_factory_year() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.factory_year_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int32_t Car::factory_year() const {
  // @@protoc_insertion_point(field_get:sample.Car.factory_year)
  return _internal_factory_year();
}
inline void Car::set_factory_year(::int32_t value) {
  _internal_set_factory_year(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:sample.Car.factory_year)
}
inline ::int32_t Car::_internal_factory_year() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.factory_year_;
}
inline void Car::_internal_set_factory_year(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.factory_year_ = value;
}

// string license_plate = 3;
inline void Car::clear_license_plate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.license_plate_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& Car::license_plate() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:sample.Car.license_plate)
  return _internal_license_plate();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Car::set_license_plate(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.license_plate_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:sample.Car.license_plate)
}
inline ::std::string* PROTOBUF_NONNULL Car::mutable_license_plate()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_license_plate();
  // @@protoc_insertion_point(field_mutable:sample.Car.license_plate)
  return _s;
}
inline const ::std::string& Car::_internal_license_plate() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.license_plate_.Get();
}
inline void Car::_internal_set_license_plate(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.license_plate_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Car::_internal_mutable_license_plate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.license_plate_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Car::release_license_plate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:sample.Car.license_plate)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.license_plate_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.license_plate_.Set("", GetArena());
  }
  return released;
}
inline void Car::set_allocated_license_plate(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.license_plate_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.license_plate_.IsDefault()) {
    _impl_.license_plate_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:sample.Car.license_plate)
}

// -------------------------------------------------------------------

// Home

// string address = 1;
inline void Home::clear_address() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.address_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& Home::address() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:sample.Home.address)
  return _internal_address();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Home::set_address(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.address_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:sample.Home.address)
}
inline ::std::string* PROTOBUF_NONNULL Home::mutable_address()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_address();
  // @@protoc_insertion_point(field_mutable:sample.Home.address)
  return _s;
}
inline const ::std::string& Home::_internal_address() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.address_.Get();
}
inline void Home::_internal_set_address(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.address_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Home::_internal_mutable_address() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.address_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Home::release_address() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:sample.Home.address)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.address_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.address_.Set("", GetArena());
  }
  return released;
}
inline void Home::set_allocated_address(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.address_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.address_.IsDefault()) {
    _impl_.address_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:sample.Home.address)
}

// string ownership = 2;
inline void Home::clear_ownership() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ownership_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& Home::ownership() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:sample.Home.ownership)
  return _internal_ownership();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Home::set_ownership(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.ownership_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:sample.Home.ownership)
}
inline ::std::string* PROTOBUF_NONNULL Home::mutable_ownership()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_ownership();
  // @@protoc_insertion_point(field_mutable:sample.Home.ownership)
  return _s;
}
inline const ::std::string& Home::_internal_ownership() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ownership_.Get();
}
inline void Home::_internal_set_ownership(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ownership_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Home::_internal_mutable_ownership() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.ownership_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Home::release_ownership() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:sample.Home.ownership)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.ownership_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.ownership_.Set("", GetArena());
  }
  return released;
}
inline void Home::set_allocated_ownership(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.ownership_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.ownership_.IsDefault()) {
    _impl_.ownership_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:sample.Home.ownership)
}

// -------------------------------------------------------------------

// PersonFirst

// string name = 1;
inline void PersonFirst::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& PersonFirst::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:sample.PersonFirst.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PersonFirst::set_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:sample.PersonFirst.name)
}
inline ::std::string* PROTOBUF_NONNULL PersonFirst::mutable_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:sample.PersonFirst.name)
  return _s;
}
inline const ::std::string& PersonFirst::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void PersonFirst::_internal_set_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PersonFirst::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PersonFirst::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:sample.PersonFirst.name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.name_.Set("", GetArena());
  }
  return released;
}
inline void PersonFirst::set_allocated_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:sample.PersonFirst.name)
}

// .sample.Born born = 2;
inline bool PersonFirst::has_born() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  PROTOBUF_ASSUME(!value || _impl_.born_ != nullptr);
  return value;
}
inline void PersonFirst::clear_born() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.born_ != nullptr) _impl_.born_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::sample::Born& PersonFirst::_internal_born() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::sample::Born* p = _impl_.born_;
  return p != nullptr ? *p : reinterpret_cast<const ::sample::Born&>(::sample::_Born_default_instance_);
}
inline const ::sample::Born& PersonFirst::born() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:sample.PersonFirst.born)
  return _internal_born();
}
inline void PersonFirst::unsafe_arena_set_allocated_born(
    ::sample::Born* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.born_);
  }
  _impl_.born_ = reinterpret_cast<::sample::Born*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:sample.PersonFirst.born)
}
inline ::sample::Born* PROTOBUF_NULLABLE PersonFirst::release_born() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::sample::Born* released = _impl_.born_;
  _impl_.born_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::sample::Born* PROTOBUF_NULLABLE PersonFirst::unsafe_arena_release_born() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:sample.PersonFirst.born)

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::sample::Born* temp = _impl_.born_;
  _impl_.born_ = nullptr;
  return temp;
}
inline ::sample::Born* PROTOBUF_NONNULL PersonFirst::_internal_mutable_born() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.born_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::sample::Born>(GetArena());
    _impl_.born_ = reinterpret_cast<::sample::Born*>(p);
  }
  return _impl_.born_;
}
inline ::sample::Born* PROTOBUF_NONNULL PersonFirst::mutable_born()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::sample::Born* _msg = _internal_mutable_born();
  // @@protoc_insertion_point(field_mutable:sample.PersonFirst.born)
  return _msg;
}
inline void PersonFirst::set_allocated_born(::sample::Born* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.born_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }

  _impl_.born_ = reinterpret_cast<::sample::Born*>(value);
  // @@protoc_insertion_point(field_set_allocated:sample.PersonFirst.born)
}

// .sample.Car car = 3;
inline bool PersonFirst::has_car() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  PROTOBUF_ASSUME(!value || _impl_.car_ != nullptr);
  return value;
}
inline void PersonFirst::clear_car() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.car_ != nullptr) _impl_.car_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline const ::sample::Car& PersonFirst::_internal_car() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::sample::Car* p = _impl_.car_;
  return p != nullptr ? *p : reinterpret_cast<const ::sample::Car&>(::sample::_Car_default_instance_);
}
inline const ::sample::Car& PersonFirst::car() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:sample.PersonFirst.car)
  return _internal_car();
}
inline void PersonFirst::unsafe_arena_set_allocated_car(
    ::sample::Car* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.car_);
  }
  _impl_.car_ = reinterpret_cast<::sample::Car*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:sample.PersonFirst.car)
}
inline ::sample::Car* PROTOBUF_NULLABLE PersonFirst::release_car() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::sample::Car* released = _impl_.car_;
  _impl_.car_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::sample::Car* PROTOBUF_NULLABLE PersonFirst::unsafe_arena_release_car() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:sample.PersonFirst.car)

  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::sample::Car* temp = _impl_.car_;
  _impl_.car_ = nullptr;
  return temp;
}
inline ::sample::Car* PROTOBUF_NONNULL PersonFirst::_internal_mutable_car() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.car_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::sample::Car>(GetArena());
    _impl_.car_ = reinterpret_cast<::sample::Car*>(p);
  }
  return _impl_.car_;
}
inline ::sample::Car* PROTOBUF_NONNULL PersonFirst::mutable_car()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::sample::Car* _msg = _internal_mutable_car();
  // @@protoc_insertion_point(field_mutable:sample.PersonFirst.car)
  return _msg;
}
inline void PersonFirst::set_allocated_car(::sample::Car* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.car_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }

  _impl_.car_ = reinterpret_cast<::sample::Car*>(value);
  // @@protoc_insertion_point(field_set_allocated:sample.PersonFirst.car)
}

// .sample.Home home = 4;
inline bool PersonFirst::has_home() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000010U);
  PROTOBUF_ASSUME(!value || _impl_.home_ != nullptr);
  return value;
}
inline void PersonFirst::clear_home() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.home_ != nullptr) _impl_.home_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline const ::sample::Home& PersonFirst::_internal_home() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::sample::Home* p = _impl_.home_;
  return p != nullptr ? *p : reinterpret_cast<const ::sample::Home&>(::sample::_Home_default_instance_);
}
inline const ::sample::Home& PersonFirst::home() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:sample.PersonFirst.home)
  return _internal_home();
}
inline void PersonFirst::unsafe_arena_set_allocated_home(
    ::sample::Home* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.home_);
  }
  _impl_.home_ = reinterpret_cast<::sample::Home*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:sample.PersonFirst.home)
}
inline ::sample::Home* PROTOBUF_NULLABLE PersonFirst::release_home() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::sample::Home* released = _impl_.home_;
  _impl_.home_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::sample::Home* PROTOBUF_NULLABLE PersonFirst::unsafe_arena_release_home() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:sample.PersonFirst.home)

  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::sample::Home* temp = _impl_.home_;
  _impl_.home_ = nullptr;
  return temp;
}
inline ::sample::Home* PROTOBUF_NONNULL PersonFirst::_internal_mutable_home() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.home_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::sample::Home>(GetArena());
    _impl_.home_ = reinterpret_cast<::sample::Home*>(p);
  }
  return _impl_.home_;
}
inline ::sample::Home* PROTOBUF_NONNULL PersonFirst::mutable_home()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::sample::Home* _msg = _internal_mutable_home();
  // @@protoc_insertion_point(field_mutable:sample.PersonFirst.home)
  return _msg;
}
inline void PersonFirst::set_allocated_home(::sample::Home* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.home_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  }

  _impl_.home_ = reinterpret_cast<::sample::Home*>(value);
  // @@protoc_insertion_point(field_set_allocated:sample.PersonFirst.home)
}

// string job = 5;
inline void PersonFirst::clear_job() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.job_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& PersonFirst::job() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:sample.PersonFirst.job)
  return _internal_job();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PersonFirst::set_job(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.job_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:sample.PersonFirst.job)
}
inline ::std::string* PROTOBUF_NONNULL PersonFirst::mutable_job()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_job();
  // @@protoc_insertion_point(field_mutable:sample.PersonFirst.job)
  return _s;
}
inline const ::std::string& PersonFirst::_internal_job() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.job_.Get();
}
inline void PersonFirst::_internal_set_job(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.job_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PersonFirst::_internal_mutable_job() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.job_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PersonFirst::release_job() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:sample.PersonFirst.job)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.job_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.job_.Set("", GetArena());
  }
  return released;
}
inline void PersonFirst::set_allocated_job(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.job_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.job_.IsDefault()) {
    _impl_.job_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:sample.PersonFirst.job)
}

// -------------------------------------------------------------------

// PeopleFirst

// repeated .sample.PersonFirst people = 1;
inline int PeopleFirst::_internal_people_size() const {
  return _internal_people().size();
}
inline int PeopleFirst::people_size() const {
  return _internal_people_size();
}
inline void PeopleFirst::clear_people() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.people_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::sample::PersonFirst* PROTOBUF_NONNULL PeopleFirst::mutable_people(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:sample.PeopleFirst.people)
  return _internal_mutable_people()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::sample::PersonFirst>* PROTOBUF_NONNULL PeopleFirst::mutable_people()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:sample.PeopleFirst.people)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_people();
}
inline const ::sample::PersonFirst& PeopleFirst::people(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:sample.PeopleFirst.people)
  return _internal_people().Get(index);
}
inline ::sample::PersonFirst* PROTOBUF_NONNULL PeopleFirst::add_people()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::sample::PersonFirst* _add = _internal_mutable_people()->Add();
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:sample.PeopleFirst.people)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::sample::PersonFirst>& PeopleFirst::people() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:sample.PeopleFirst.people)
  return _internal_people();
}
inline const ::google::protobuf::RepeatedPtrField<::sample::PersonFirst>&
PeopleFirst::_internal_people() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.people_;
}
inline ::google::protobuf::RepeatedPtrField<::sample::PersonFirst>* PROTOBUF_NONNULL
PeopleFirst::_internal_mutable_people() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.people_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace sample


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // first_2eproto_2epb_2eh
