// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: second.proto
// Protobuf C++ Version: 6.33.0-dev

#include "second.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace sample {

inline constexpr Home2::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        address_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        ownership_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR Home2::Home2(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Home2_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct Home2DefaultTypeInternal {
  PROTOBUF_CONSTEXPR Home2DefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Home2DefaultTypeInternal() {}
  union {
    Home2 _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Home2DefaultTypeInternal _Home2_default_instance_;

inline constexpr Car2::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        model_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        license_plate_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        factory_year_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Car2::Car2(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Car2_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct Car2DefaultTypeInternal {
  PROTOBUF_CONSTEXPR Car2DefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Car2DefaultTypeInternal() {}
  union {
    Car2 _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Car2DefaultTypeInternal _Car2_default_instance_;

inline constexpr Born2::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        date_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        city_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        hospital_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        father_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR Born2::Born2(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Born2_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct Born2DefaultTypeInternal {
  PROTOBUF_CONSTEXPR Born2DefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Born2DefaultTypeInternal() {}
  union {
    Born2 _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Born2DefaultTypeInternal _Born2_default_instance_;

inline constexpr PersonSecond::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        born_{nullptr},
        car_{nullptr},
        home_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR PersonSecond::PersonSecond(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PersonSecond_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PersonSecondDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PersonSecondDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PersonSecondDefaultTypeInternal() {}
  union {
    PersonSecond _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PersonSecondDefaultTypeInternal _PersonSecond_default_instance_;

inline constexpr PeopleSecond::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        people_{} {}

template <typename>
PROTOBUF_CONSTEXPR PeopleSecond::PeopleSecond(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PeopleSecond_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PeopleSecondDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PeopleSecondDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PeopleSecondDefaultTypeInternal() {}
  union {
    PeopleSecond _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PeopleSecondDefaultTypeInternal _PeopleSecond_default_instance_;
}  // namespace sample
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_second_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_second_2eproto = nullptr;
const ::uint32_t
    TableStruct_second_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::sample::Born2, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::sample::Born2, _impl_.date_),
        PROTOBUF_FIELD_OFFSET(::sample::Born2, _impl_.city_),
        PROTOBUF_FIELD_OFFSET(::sample::Born2, _impl_.hospital_name_),
        PROTOBUF_FIELD_OFFSET(::sample::Born2, _impl_.father_name_),
        0,
        1,
        2,
        3,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::sample::Car2, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::sample::Car2, _impl_.model_name_),
        PROTOBUF_FIELD_OFFSET(::sample::Car2, _impl_.factory_year_),
        PROTOBUF_FIELD_OFFSET(::sample::Car2, _impl_.license_plate_),
        0,
        2,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::sample::Home2, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::sample::Home2, _impl_.address_),
        PROTOBUF_FIELD_OFFSET(::sample::Home2, _impl_.ownership_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::sample::PersonSecond, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::sample::PersonSecond, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::sample::PersonSecond, _impl_.born_),
        PROTOBUF_FIELD_OFFSET(::sample::PersonSecond, _impl_.car_),
        PROTOBUF_FIELD_OFFSET(::sample::PersonSecond, _impl_.home_),
        0,
        1,
        2,
        3,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::sample::PeopleSecond, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::sample::PeopleSecond, _impl_.people_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::sample::Born2)},
        {11, sizeof(::sample::Car2)},
        {20, sizeof(::sample::Home2)},
        {27, sizeof(::sample::PersonSecond)},
        {38, sizeof(::sample::PeopleSecond)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::sample::_Born2_default_instance_._instance,
    &::sample::_Car2_default_instance_._instance,
    &::sample::_Home2_default_instance_._instance,
    &::sample::_PersonSecond_default_instance_._instance,
    &::sample::_PeopleSecond_default_instance_._instance,
};
const char descriptor_table_protodef_second_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014second.proto\022\006sample\"O\n\005Born2\022\014\n\004date\030"
    "\001 \001(\t\022\014\n\004city\030\002 \001(\t\022\025\n\rhospital_name\030\003 \001"
    "(\t\022\023\n\013father_name\030\004 \001(\t\"G\n\004Car2\022\022\n\nmodel"
    "_name\030\001 \001(\t\022\024\n\014factory_year\030\002 \001(\005\022\025\n\rlic"
    "ense_plate\030\003 \001(\t\"+\n\005Home2\022\017\n\007address\030\001 \001"
    "(\t\022\021\n\townership\030\002 \001(\t\"q\n\014PersonSecond\022\014\n"
    "\004name\030\001 \001(\t\022\033\n\004born\030\002 \001(\0132\r.sample.Born2"
    "\022\031\n\003car\030\003 \001(\0132\014.sample.Car2\022\033\n\004home\030\004 \001("
    "\0132\r.sample.Home2\"4\n\014PeopleSecond\022$\n\006peop"
    "le\030\001 \003(\0132\024.sample.PersonSecondb\006proto3"
};
static ::absl::once_flag descriptor_table_second_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_second_2eproto = {
    false,
    false,
    398,
    descriptor_table_protodef_second_2eproto,
    "second.proto",
    &descriptor_table_second_2eproto_once,
    nullptr,
    0,
    5,
    schemas,
    file_default_instances,
    TableStruct_second_2eproto::offsets,
    file_level_enum_descriptors_second_2eproto,
    file_level_service_descriptors_second_2eproto,
};
namespace sample {
// ===================================================================

class Born2::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Born2>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Born2, _impl_._has_bits_);
};

Born2::Born2(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Born2_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:sample.Born2)
}
PROTOBUF_NDEBUG_INLINE Born2::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::sample::Born2& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        date_(arena, from.date_),
        city_(arena, from.city_),
        hospital_name_(arena, from.hospital_name_),
        father_name_(arena, from.father_name_) {}

Born2::Born2(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Born2& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Born2_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Born2* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:sample.Born2)
}
PROTOBUF_NDEBUG_INLINE Born2::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        date_(arena),
        city_(arena),
        hospital_name_(arena),
        father_name_(arena) {}

inline void Born2::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Born2::~Born2() {
  // @@protoc_insertion_point(destructor:sample.Born2)
  SharedDtor(*this);
}
inline void Born2::SharedDtor(MessageLite& self) {
  Born2& this_ = static_cast<Born2&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.date_.Destroy();
  this_._impl_.city_.Destroy();
  this_._impl_.hospital_name_.Destroy();
  this_._impl_.father_name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Born2::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Born2(arena);
}
constexpr auto Born2::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Born2),
                                            alignof(Born2));
}
constexpr auto Born2::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Born2_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Born2::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Born2>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Born2::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Born2>(), &Born2::ByteSizeLong,
              &Born2::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Born2, _impl_._cached_size_),
          false,
      },
      &Born2::kDescriptorMethods,
      &descriptor_table_second_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Born2_class_data_ =
        Born2::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Born2::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Born2_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Born2_class_data_.tc_table);
  return Born2_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 53, 2>
Born2::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Born2, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Born2_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::sample::Born2>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string father_name = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 3, 0, PROTOBUF_FIELD_OFFSET(Born2, _impl_.father_name_)}},
    // string date = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(Born2, _impl_.date_)}},
    // string city = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(Born2, _impl_.city_)}},
    // string hospital_name = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 2, 0, PROTOBUF_FIELD_OFFSET(Born2, _impl_.hospital_name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string date = 1;
    {PROTOBUF_FIELD_OFFSET(Born2, _impl_.date_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string city = 2;
    {PROTOBUF_FIELD_OFFSET(Born2, _impl_.city_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string hospital_name = 3;
    {PROTOBUF_FIELD_OFFSET(Born2, _impl_.hospital_name_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string father_name = 4;
    {PROTOBUF_FIELD_OFFSET(Born2, _impl_.father_name_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\14\4\4\15\13\0\0\0"
    "sample.Born2"
    "date"
    "city"
    "hospital_name"
    "father_name"
  }},
};
PROTOBUF_NOINLINE void Born2::Clear() {
// @@protoc_insertion_point(message_clear_start:sample.Born2)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.date_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.city_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.hospital_name_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _impl_.father_name_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Born2::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Born2& this_ = static_cast<const Born2&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Born2::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Born2& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:sample.Born2)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string date = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_date().empty()) {
      const ::std::string& _s = this_._internal_date();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "sample.Born2.date");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // string city = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_city().empty()) {
      const ::std::string& _s = this_._internal_city();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "sample.Born2.city");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // string hospital_name = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_hospital_name().empty()) {
      const ::std::string& _s = this_._internal_hospital_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "sample.Born2.hospital_name");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  // string father_name = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (!this_._internal_father_name().empty()) {
      const ::std::string& _s = this_._internal_father_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "sample.Born2.father_name");
      target = stream->WriteStringMaybeAliased(4, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sample.Born2)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Born2::ByteSizeLong(const MessageLite& base) {
  const Born2& this_ = static_cast<const Born2&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Born2::ByteSizeLong() const {
  const Born2& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:sample.Born2)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // string date = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_date().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_date());
      }
    }
    // string city = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_city().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_city());
      }
    }
    // string hospital_name = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_hospital_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_hospital_name());
      }
    }
    // string father_name = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!this_._internal_father_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_father_name());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Born2::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Born2*>(&to_msg);
  auto& from = static_cast<const Born2&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:sample.Born2)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_date().empty()) {
        _this->_internal_set_date(from._internal_date());
      } else {
        if (_this->_impl_.date_.IsDefault()) {
          _this->_internal_set_date("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_city().empty()) {
        _this->_internal_set_city(from._internal_city());
      } else {
        if (_this->_impl_.city_.IsDefault()) {
          _this->_internal_set_city("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_hospital_name().empty()) {
        _this->_internal_set_hospital_name(from._internal_hospital_name());
      } else {
        if (_this->_impl_.hospital_name_.IsDefault()) {
          _this->_internal_set_hospital_name("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!from._internal_father_name().empty()) {
        _this->_internal_set_father_name(from._internal_father_name());
      } else {
        if (_this->_impl_.father_name_.IsDefault()) {
          _this->_internal_set_father_name("");
        }
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Born2::CopyFrom(const Born2& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:sample.Born2)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Born2::InternalSwap(Born2* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.date_, &other->_impl_.date_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.city_, &other->_impl_.city_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.hospital_name_, &other->_impl_.hospital_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.father_name_, &other->_impl_.father_name_, arena);
}

::google::protobuf::Metadata Born2::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Car2::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Car2>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Car2, _impl_._has_bits_);
};

Car2::Car2(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Car2_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:sample.Car2)
}
PROTOBUF_NDEBUG_INLINE Car2::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::sample::Car2& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        model_name_(arena, from.model_name_),
        license_plate_(arena, from.license_plate_) {}

Car2::Car2(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Car2& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Car2_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Car2* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.factory_year_ = from._impl_.factory_year_;

  // @@protoc_insertion_point(copy_constructor:sample.Car2)
}
PROTOBUF_NDEBUG_INLINE Car2::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        model_name_(arena),
        license_plate_(arena) {}

inline void Car2::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.factory_year_ = {};
}
Car2::~Car2() {
  // @@protoc_insertion_point(destructor:sample.Car2)
  SharedDtor(*this);
}
inline void Car2::SharedDtor(MessageLite& self) {
  Car2& this_ = static_cast<Car2&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.model_name_.Destroy();
  this_._impl_.license_plate_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Car2::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Car2(arena);
}
constexpr auto Car2::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Car2),
                                            alignof(Car2));
}
constexpr auto Car2::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Car2_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Car2::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Car2>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Car2::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Car2>(), &Car2::ByteSizeLong,
              &Car2::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Car2, _impl_._cached_size_),
          false,
      },
      &Car2::kDescriptorMethods,
      &descriptor_table_second_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Car2_class_data_ =
        Car2::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Car2::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Car2_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Car2_class_data_.tc_table);
  return Car2_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 43, 2>
Car2::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Car2, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Car2_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::sample::Car2>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string model_name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(Car2, _impl_.model_name_)}},
    // int32 factory_year = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Car2, _impl_.factory_year_), 2>(),
     {16, 2, 0, PROTOBUF_FIELD_OFFSET(Car2, _impl_.factory_year_)}},
    // string license_plate = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 1, 0, PROTOBUF_FIELD_OFFSET(Car2, _impl_.license_plate_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string model_name = 1;
    {PROTOBUF_FIELD_OFFSET(Car2, _impl_.model_name_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 factory_year = 2;
    {PROTOBUF_FIELD_OFFSET(Car2, _impl_.factory_year_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // string license_plate = 3;
    {PROTOBUF_FIELD_OFFSET(Car2, _impl_.license_plate_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\13\12\0\15\0\0\0\0"
    "sample.Car2"
    "model_name"
    "license_plate"
  }},
};
PROTOBUF_NOINLINE void Car2::Clear() {
// @@protoc_insertion_point(message_clear_start:sample.Car2)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.model_name_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.license_plate_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.factory_year_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Car2::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Car2& this_ = static_cast<const Car2&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Car2::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Car2& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:sample.Car2)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string model_name = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_model_name().empty()) {
      const ::std::string& _s = this_._internal_model_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "sample.Car2.model_name");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // int32 factory_year = 2;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_factory_year() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
              stream, this_._internal_factory_year(), target);
    }
  }

  // string license_plate = 3;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_license_plate().empty()) {
      const ::std::string& _s = this_._internal_license_plate();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "sample.Car2.license_plate");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sample.Car2)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Car2::ByteSizeLong(const MessageLite& base) {
  const Car2& this_ = static_cast<const Car2&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Car2::ByteSizeLong() const {
  const Car2& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:sample.Car2)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // string model_name = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_model_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_model_name());
      }
    }
    // string license_plate = 3;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_license_plate().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_license_plate());
      }
    }
    // int32 factory_year = 2;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_factory_year() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_factory_year());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Car2::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Car2*>(&to_msg);
  auto& from = static_cast<const Car2&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:sample.Car2)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_model_name().empty()) {
        _this->_internal_set_model_name(from._internal_model_name());
      } else {
        if (_this->_impl_.model_name_.IsDefault()) {
          _this->_internal_set_model_name("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_license_plate().empty()) {
        _this->_internal_set_license_plate(from._internal_license_plate());
      } else {
        if (_this->_impl_.license_plate_.IsDefault()) {
          _this->_internal_set_license_plate("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_factory_year() != 0) {
        _this->_impl_.factory_year_ = from._impl_.factory_year_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Car2::CopyFrom(const Car2& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:sample.Car2)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Car2::InternalSwap(Car2* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.model_name_, &other->_impl_.model_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.license_plate_, &other->_impl_.license_plate_, arena);
  swap(_impl_.factory_year_, other->_impl_.factory_year_);
}

::google::protobuf::Metadata Car2::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Home2::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Home2>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Home2, _impl_._has_bits_);
};

Home2::Home2(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Home2_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:sample.Home2)
}
PROTOBUF_NDEBUG_INLINE Home2::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::sample::Home2& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        address_(arena, from.address_),
        ownership_(arena, from.ownership_) {}

Home2::Home2(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Home2& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Home2_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Home2* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:sample.Home2)
}
PROTOBUF_NDEBUG_INLINE Home2::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        address_(arena),
        ownership_(arena) {}

inline void Home2::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Home2::~Home2() {
  // @@protoc_insertion_point(destructor:sample.Home2)
  SharedDtor(*this);
}
inline void Home2::SharedDtor(MessageLite& self) {
  Home2& this_ = static_cast<Home2&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.address_.Destroy();
  this_._impl_.ownership_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Home2::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Home2(arena);
}
constexpr auto Home2::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Home2),
                                            alignof(Home2));
}
constexpr auto Home2::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Home2_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Home2::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Home2>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Home2::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Home2>(), &Home2::ByteSizeLong,
              &Home2::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Home2, _impl_._cached_size_),
          false,
      },
      &Home2::kDescriptorMethods,
      &descriptor_table_second_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Home2_class_data_ =
        Home2::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Home2::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Home2_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Home2_class_data_.tc_table);
  return Home2_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 37, 2>
Home2::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Home2, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Home2_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::sample::Home2>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string ownership = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(Home2, _impl_.ownership_)}},
    // string address = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(Home2, _impl_.address_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string address = 1;
    {PROTOBUF_FIELD_OFFSET(Home2, _impl_.address_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string ownership = 2;
    {PROTOBUF_FIELD_OFFSET(Home2, _impl_.ownership_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\14\7\11\0\0\0\0\0"
    "sample.Home2"
    "address"
    "ownership"
  }},
};
PROTOBUF_NOINLINE void Home2::Clear() {
// @@protoc_insertion_point(message_clear_start:sample.Home2)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.address_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.ownership_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Home2::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Home2& this_ = static_cast<const Home2&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Home2::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Home2& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:sample.Home2)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string address = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_address().empty()) {
      const ::std::string& _s = this_._internal_address();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "sample.Home2.address");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // string ownership = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_ownership().empty()) {
      const ::std::string& _s = this_._internal_ownership();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "sample.Home2.ownership");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sample.Home2)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Home2::ByteSizeLong(const MessageLite& base) {
  const Home2& this_ = static_cast<const Home2&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Home2::ByteSizeLong() const {
  const Home2& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:sample.Home2)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // string address = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_address().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_address());
      }
    }
    // string ownership = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_ownership().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_ownership());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Home2::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Home2*>(&to_msg);
  auto& from = static_cast<const Home2&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:sample.Home2)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_address().empty()) {
        _this->_internal_set_address(from._internal_address());
      } else {
        if (_this->_impl_.address_.IsDefault()) {
          _this->_internal_set_address("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_ownership().empty()) {
        _this->_internal_set_ownership(from._internal_ownership());
      } else {
        if (_this->_impl_.ownership_.IsDefault()) {
          _this->_internal_set_ownership("");
        }
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Home2::CopyFrom(const Home2& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:sample.Home2)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Home2::InternalSwap(Home2* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.address_, &other->_impl_.address_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.ownership_, &other->_impl_.ownership_, arena);
}

::google::protobuf::Metadata Home2::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PersonSecond::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PersonSecond>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PersonSecond, _impl_._has_bits_);
};

PersonSecond::PersonSecond(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PersonSecond_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:sample.PersonSecond)
}
PROTOBUF_NDEBUG_INLINE PersonSecond::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::sample::PersonSecond& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        name_(arena, from.name_) {}

PersonSecond::PersonSecond(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PersonSecond& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PersonSecond_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PersonSecond* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.born_ = (CheckHasBit(cached_has_bits, 0x00000002U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.born_)
                : nullptr;
  _impl_.car_ = (CheckHasBit(cached_has_bits, 0x00000004U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.car_)
                : nullptr;
  _impl_.home_ = (CheckHasBit(cached_has_bits, 0x00000008U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.home_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:sample.PersonSecond)
}
PROTOBUF_NDEBUG_INLINE PersonSecond::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        name_(arena) {}

inline void PersonSecond::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, born_),
           0,
           offsetof(Impl_, home_) -
               offsetof(Impl_, born_) +
               sizeof(Impl_::home_));
}
PersonSecond::~PersonSecond() {
  // @@protoc_insertion_point(destructor:sample.PersonSecond)
  SharedDtor(*this);
}
inline void PersonSecond::SharedDtor(MessageLite& self) {
  PersonSecond& this_ = static_cast<PersonSecond&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  delete this_._impl_.born_;
  delete this_._impl_.car_;
  delete this_._impl_.home_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PersonSecond::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PersonSecond(arena);
}
constexpr auto PersonSecond::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PersonSecond),
                                            alignof(PersonSecond));
}
constexpr auto PersonSecond::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PersonSecond_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PersonSecond::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PersonSecond>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PersonSecond::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PersonSecond>(), &PersonSecond::ByteSizeLong,
              &PersonSecond::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PersonSecond, _impl_._cached_size_),
          false,
      },
      &PersonSecond::kDescriptorMethods,
      &descriptor_table_second_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PersonSecond_class_data_ =
        PersonSecond::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PersonSecond::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PersonSecond_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PersonSecond_class_data_.tc_table);
  return PersonSecond_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 3, 32, 2>
PersonSecond::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PersonSecond, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    PersonSecond_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::sample::PersonSecond>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .sample.Home2 home = 4;
    {::_pbi::TcParser::FastMtS1,
     {34, 3, 2, PROTOBUF_FIELD_OFFSET(PersonSecond, _impl_.home_)}},
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(PersonSecond, _impl_.name_)}},
    // .sample.Born2 born = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(PersonSecond, _impl_.born_)}},
    // .sample.Car2 car = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 2, 1, PROTOBUF_FIELD_OFFSET(PersonSecond, _impl_.car_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(PersonSecond, _impl_.name_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .sample.Born2 born = 2;
    {PROTOBUF_FIELD_OFFSET(PersonSecond, _impl_.born_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .sample.Car2 car = 3;
    {PROTOBUF_FIELD_OFFSET(PersonSecond, _impl_.car_), _Internal::kHasBitsOffset + 2, 1, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .sample.Home2 home = 4;
    {PROTOBUF_FIELD_OFFSET(PersonSecond, _impl_.home_), _Internal::kHasBitsOffset + 3, 2, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::sample::Born2>()},
      {::_pbi::TcParser::GetTable<::sample::Car2>()},
      {::_pbi::TcParser::GetTable<::sample::Home2>()},
  }},
  {{
    "\23\4\0\0\0\0\0\0"
    "sample.PersonSecond"
    "name"
  }},
};
PROTOBUF_NOINLINE void PersonSecond::Clear() {
// @@protoc_insertion_point(message_clear_start:sample.PersonSecond)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.name_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(_impl_.born_ != nullptr);
      _impl_.born_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(_impl_.car_ != nullptr);
      _impl_.car_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(_impl_.home_ != nullptr);
      _impl_.home_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PersonSecond::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PersonSecond& this_ = static_cast<const PersonSecond&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PersonSecond::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PersonSecond& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:sample.PersonSecond)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string name = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_name().empty()) {
      const ::std::string& _s = this_._internal_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "sample.PersonSecond.name");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // .sample.Born2 born = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.born_, this_._impl_.born_->GetCachedSize(), target,
        stream);
  }

  // .sample.Car2 car = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *this_._impl_.car_, this_._impl_.car_->GetCachedSize(), target,
        stream);
  }

  // .sample.Home2 home = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        4, *this_._impl_.home_, this_._impl_.home_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sample.PersonSecond)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PersonSecond::ByteSizeLong(const MessageLite& base) {
  const PersonSecond& this_ = static_cast<const PersonSecond&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PersonSecond::ByteSizeLong() const {
  const PersonSecond& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:sample.PersonSecond)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // string name = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_name());
      }
    }
    // .sample.Born2 born = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.born_);
    }
    // .sample.Car2 car = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.car_);
    }
    // .sample.Home2 home = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.home_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PersonSecond::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<PersonSecond*>(&to_msg);
  auto& from = static_cast<const PersonSecond&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:sample.PersonSecond)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_name().empty()) {
        _this->_internal_set_name(from._internal_name());
      } else {
        if (_this->_impl_.name_.IsDefault()) {
          _this->_internal_set_name("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(from._impl_.born_ != nullptr);
      if (_this->_impl_.born_ == nullptr) {
        _this->_impl_.born_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.born_);
      } else {
        _this->_impl_.born_->MergeFrom(*from._impl_.born_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(from._impl_.car_ != nullptr);
      if (_this->_impl_.car_ == nullptr) {
        _this->_impl_.car_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.car_);
      } else {
        _this->_impl_.car_->MergeFrom(*from._impl_.car_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(from._impl_.home_ != nullptr);
      if (_this->_impl_.home_ == nullptr) {
        _this->_impl_.home_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.home_);
      } else {
        _this->_impl_.home_->MergeFrom(*from._impl_.home_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void PersonSecond::CopyFrom(const PersonSecond& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:sample.PersonSecond)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PersonSecond::InternalSwap(PersonSecond* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PersonSecond, _impl_.home_)
      + sizeof(PersonSecond::_impl_.home_)
      - PROTOBUF_FIELD_OFFSET(PersonSecond, _impl_.born_)>(
          reinterpret_cast<char*>(&_impl_.born_),
          reinterpret_cast<char*>(&other->_impl_.born_));
}

::google::protobuf::Metadata PersonSecond::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PeopleSecond::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PeopleSecond>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PeopleSecond, _impl_._has_bits_);
};

PeopleSecond::PeopleSecond(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PeopleSecond_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:sample.PeopleSecond)
}
PROTOBUF_NDEBUG_INLINE PeopleSecond::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::sample::PeopleSecond& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        people_{visibility, arena, from.people_} {}

PeopleSecond::PeopleSecond(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PeopleSecond& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PeopleSecond_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PeopleSecond* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:sample.PeopleSecond)
}
PROTOBUF_NDEBUG_INLINE PeopleSecond::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        people_{visibility, arena} {}

inline void PeopleSecond::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PeopleSecond::~PeopleSecond() {
  // @@protoc_insertion_point(destructor:sample.PeopleSecond)
  SharedDtor(*this);
}
inline void PeopleSecond::SharedDtor(MessageLite& self) {
  PeopleSecond& this_ = static_cast<PeopleSecond&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PeopleSecond::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PeopleSecond(arena);
}
constexpr auto PeopleSecond::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(PeopleSecond, _impl_.people_) +
          decltype(PeopleSecond::_impl_.people_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(PeopleSecond), alignof(PeopleSecond), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&PeopleSecond::PlacementNew_,
                                 sizeof(PeopleSecond),
                                 alignof(PeopleSecond));
  }
}
constexpr auto PeopleSecond::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PeopleSecond_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PeopleSecond::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PeopleSecond>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PeopleSecond::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PeopleSecond>(), &PeopleSecond::ByteSizeLong,
              &PeopleSecond::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PeopleSecond, _impl_._cached_size_),
          false,
      },
      &PeopleSecond::kDescriptorMethods,
      &descriptor_table_second_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PeopleSecond_class_data_ =
        PeopleSecond::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PeopleSecond::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PeopleSecond_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PeopleSecond_class_data_.tc_table);
  return PeopleSecond_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
PeopleSecond::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PeopleSecond, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    PeopleSecond_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::sample::PeopleSecond>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .sample.PersonSecond people = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(PeopleSecond, _impl_.people_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .sample.PersonSecond people = 1;
    {PROTOBUF_FIELD_OFFSET(PeopleSecond, _impl_.people_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::sample::PersonSecond>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void PeopleSecond::Clear() {
// @@protoc_insertion_point(message_clear_start:sample.PeopleSecond)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _impl_.people_.Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PeopleSecond::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PeopleSecond& this_ = static_cast<const PeopleSecond&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PeopleSecond::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PeopleSecond& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:sample.PeopleSecond)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated .sample.PersonSecond people = 1;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_people_size());
         i < n; i++) {
      const auto& repfield = this_._internal_people().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              1, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sample.PeopleSecond)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PeopleSecond::ByteSizeLong(const MessageLite& base) {
  const PeopleSecond& this_ = static_cast<const PeopleSecond&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PeopleSecond::ByteSizeLong() const {
  const PeopleSecond& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:sample.PeopleSecond)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .sample.PersonSecond people = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_people_size();
      for (const auto& msg : this_._internal_people()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PeopleSecond::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<PeopleSecond*>(&to_msg);
  auto& from = static_cast<const PeopleSecond&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:sample.PeopleSecond)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _this->_internal_mutable_people()->MergeFrom(
        from._internal_people());
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void PeopleSecond::CopyFrom(const PeopleSecond& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:sample.PeopleSecond)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PeopleSecond::InternalSwap(PeopleSecond* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.people_.InternalSwap(&other->_impl_.people_);
}

::google::protobuf::Metadata PeopleSecond::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace sample
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_second_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
